### PR TITLE
ability to set up one-way tls with the wizard

### PR DESCRIPTION
**Pull request by theashiot**

### CODE REVIEW

**Review by skyllarr — COMMENTED** [review]
@theashiot Just a minor, please put a copyright header to all of the files. Thanks!

**Comment by theashiot** [comment]
Thanks, @Skyllarr ! Done.

**Comment by theashiot** [comment]
Hi @fjuma, can you please review the PR?

thanks,
ashwin

**Comment by darranl** [comment]
@theashiot Should we get this merged as-is - as an incubator project we can then decide to create issues and work incrementally as time allows / based on other priorites?

**Comment by theashiot** [comment]
> @theashiot Should we get this merged as-is - as an incubator project we can then decide to create issues and work incrementally as time allows / based on other priorites?

That sounds like a good plan, thanks!

**Pull request merged**
